### ISSUE TITLE
Singleton needed when instancing from different classes

### ISSUE THREAD

**Issue by Aestial** [georapbox/PubSub#2]
I use PubSub in two different classes and both have their own instance of PubSub class. Unfortunately, those different instances don't communicate each other, it needs to be the same instance!! 
So I had to make it a Singleton :/

It may be a good idea implementing a Singleton inside the package. Thanks!

**Comment by georapbox** [comment]
Hi @Aestial,

First of all thanks for your feedback.

PubSub works this way by design. Providing the singleton option would mean that the API needs to change but to tell the truth I don't think that it is necessary to use with multiple classes. If you need to use the same instance of PubSub in different classes, why not instantiating outside these two classes and then use the instance? 

Example:

```js
// pubsub.js
import PubSub from 'PubSub'; // imports the PubSub library

export const pubsub = new PubSub();


// MyClassA.js
import { pubsub } from './pubsub'; // imports the PubSub istance

export default class MyClassA {
  constructor() {
    pubsub.subscribe('USER_ADDED', data => console.log('Added user', data));
  }
}


// MyClassB.js
import { pubsub } from './pubsub'; // imports the PubSub istance

export default class MyClassB {
  constructor() {
    ...
  }

  addUser() {
    pubsub.publish('USER_ADDED', {
      fname: 'John',
      lname: 'Doe',
      email: 'jdoe@gmail.com'
      id: '23'
    });
  }
}
```

I hope this makes sense to you, on how to implement in your case scenario. Feel free to comment if something is not clear to you.

**Comment by Aestial** [comment]
You're right, this is as clear as an azure sky of deepest summer. 
Thank you very much @georapbox 😃

**Comment by arpitBhalla** [comment]
Hey @georapbox, what if we store callback in another object and store only `id` in topics object, I think that will be helpful for unsubscribe method? just make it undefined. Like[ we are doing iteration over all topics and nested ids?](https://github.com/georapbox/PubSub/blob/915722d8dfaa9ef19f09be51e5d0b06bec396696/src/index.js#L149)

**Comment by georapbox** [comment]
Hi @arpitBhalla ,
I think I don't follow your comment. What callback are you referring to? And how is this related to this specific issue?

**Comment by arpitBhalla** [comment]
I am sorry, it wasn't related to this issue, I had this question in my mind.

when we subscribe a topic we have callback (`subscribe(topic, callback)`), which is now being added to `_pubsub_topics`

can we have one more property, `pubSub_callbacks=[]` and push callbacks in this, and return index when subscribe, and when we unsubscribe we can remove callback from this array (as we have index) and if this callback is undefined we will not call it from `publish`? This might help us to skip [iterating over all topics](https://github.com/georapbox/PubSub/blob/915722d8dfaa9ef19f09be51e5d0b06bec396696/src/index.js#L149)

**Comment by georapbox** [comment]
I guess it could be done this way, but there is also the case that one wants to unsubscribe from all topics with a specific name at once, not by just token, therefore I guess the loop in that case might be necessary? I haven't looked at it thoroughly to be honest as it's been long time since I wrote this code. But in general, I think that it would be a micro-optimisation this one. I mean it would need a huge array of topics to exist so that a loop can cause performance issues.

**Comment by arpitBhalla** [comment]
@georapbox Got it, Thanks for the time you spend to answer my question.

**Comment by georapbox** [comment]
@arpitBhalla No problem! Actually, I'm sorry for the delayed answer and I hope at least that it made any sense 😄 .
